{% set name = "sevenn" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sevenn-{{ version }}.tar.gz
  sha256: 5d1f95fa389128d90ce8925bad445d61b35ff5330db335eac28ac7203f66016a

build:
  entry_points:
    - sevenn = sevenn.main.sevenn:main
    - sevenn_get_model = sevenn.main.sevenn_get_model:main
    - sevenn_graph_build = sevenn.main.sevenn_graph_build:main
    - sevenn_inference = sevenn.main.sevenn_inference:main
    - sevenn_patch_lammps = sevenn.main.sevenn_patch_lammps:main
    - sevenn_preset = sevenn.main.sevenn_preset:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip:  True  # [not linux or cuda_compiler_version == "None"] 

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - {{ compiler('cuda') }} 
  host:
    - python
    - setuptools >=61.0
    - pip
    - pytorch
    - cuda-cudart
  run:
    - ninja
    - setuptools >=61.0
    - pandas
    - requests
    - matscipy
    - python
    - ase
    - braceexpand
    - pyyaml
    - e3nn >=0.5.0
    - tqdm
    - scikit-learn
    - pytorch_geometric >=2.5.0
    - numpy
    - cuda-cudart

test:
  imports:
    - sevenn
  commands:
    # - pip check
    - sevenn --help
    - sevenn_get_model --help
    - sevenn_graph_build --help
    - sevenn_inference --help
    - sevenn_patch_lammps --help
    - sevenn_preset --help
  requires:
    # - pip

about:
  home: https://github.com/MDIL-SNU/SevenNet
  summary: Scalable EquiVariance Enabled Neural Network
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
