{% set name = "sevenn" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sevenn-{{ version }}.tar.gz
  sha256: 248e4a885f5a5a42dffd3df3e7c399cbd212e4409bdc31f4b96309d6876c0b02

build:
  entry_points:
    - sevenn = sevenn.main.sevenn:main
    - sevenn_get_model = sevenn.main.sevenn_get_model:main
    - sevenn_graph_build = sevenn.main.sevenn_graph_build:main
    - sevenn_inference = sevenn.main.sevenn_inference:main
    - sevenn_patch_lammps = sevenn.main.sevenn_patch_lammps:main
    - sevenn_preset = sevenn.main.sevenn_preset:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - matscipy
    - python >=3.8
    - ase
    - braceexpand
    - pyyaml
    - e3nn
    - tqdm
    - scikit-learn
    - pytorch_geometric >=2.5.0
    - numpy <2.0

test:
  imports:
    - sevenn
  commands:
    - pip check
    - sevenn --help
    - sevenn_get_model --help
    - sevenn_graph_build --help
    - sevenn_inference --help
    - sevenn_patch_lammps --help
    - sevenn_preset --help
  requires:
    - pip

about:
  home: https://github.com/MDIL-SNU/SevenNet
  summary: Scalable EquiVariance Enabled Neural Network
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
